### ISSUE TITLE
Design para a página web

### ISSUE THREAD

**Issue by Welberth77** [Welberth77/CuidaPet#8]
### Requisitos Funcionais

- Interface Intuitiva

   - O sistema deve ser fácil de usar, com menus claros e bem organizados.

   - As informações devem ser fáceis de encontrar, usando bons títulos e seções bem definidas.

- Descrições e Etiquetas Claras
   - Todos os botões e campos devem ter nomes e explicações fáceis de entender.

   - Dicas rápidas (tooltips) e descrições adicionais devem ajudar o usuário a entender cada elemento.

### Requisitos Não Funcionais

- Consistência em Navegadores e Dispositivos

   - O sistema deve funcionar igualmente bem em todos os navegadores (como Chrome e Firefox) e dispositivos (computadores, celulares e tablets), sendo adaptável e responsivo.

**Comment by Welberth77** [comment]
Criar o design junto com o desenvolvedor do site para o alinhamento das imagens e edições necessário que vão ser utilizadas no site

**Comment by Hero13254** [comment]
Como seria a imagem? Tipo uma imagem de pets?
